services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sinso\Webcomponents\:
    resource: '../Classes/*'

  Sinso\Webcomponents\ContentObject\WebcomponentContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'WEBCOMPONENT'

  Sinso\Webcomponents\Rendering\:
    resource: '../Classes/Rendering/*'
    public: true

  Sinso\Webcomponents\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true
