services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sinso\Webcomponents\ContentObject\WebcomponentContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'WEBCOMPONENT'
