name: CI

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs

      - name: PHPStan Static Analysis
        run: composer phpstan

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
          php_version: "8.1"

      - name: PHP CS Fixer Static Analysis
        run: composer php-cs-fixer

  rector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs

      - name: Rector
        run:  composer rector
